[package]
name = "primter"
description = "Prime number iterator based on sieve of Eratosthenes"
readme = "README.md"
repository = "https://github.com/Daniikk1012/primter-rs"
version = "0.2.0"
edition = "2021"
license = "MPL-2.0"
